services:
  mini-judge:
    build: .
    environment:
      REDIS_ADDR: host.docker.internal:6379
      ROLE: all
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
